apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-ceph-rdb
#provisioner: kubernetes.io/rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.122.20:6789,192.168.122.21:6789,192.168.122.22:6789
  adminID: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kube
  userId: kube
  userSecretName: ceph-user-secret
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
