apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  namespace: lglns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv2-rwo
  resources:
    requests:
      storage: 5Gi
