apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    volumeMounts:
      - name: time
        mountPath: /etc/localtime
        readOnly: true
    command:
    - /bin/sh
    - -c
    - sleep 1000000
  hostname: busybox
  volumes:
  - hostPath:
      path: /etc/localtime
    name: time
