apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deploy-httpd
  labels:
    run: web-server
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd 
    spec:
      containers:
      - name: httpdser
        image: dockerligl/httpd:v1
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        env: test

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - nodePort: 30008
    port: 808
    targetPort: http
