apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv2-rwo
  nfs:
    path: "/nfsdata/pv2"
    server: 192.168.122.10
