apiVersion: v1
kind: ConfigMap
metadata:
  name: git
  namespace: lglns
data:
  # config为配置文件名称
  # 注意：配置文件部分要保持缩进
  config: |
    [core]
      repositoryformatversion = 0
      filemode = true
      bare = false
      logallrefupdates = true
    [remote "github"]
      url = git@github.com:gitligl/studyk8s.git
      fetch = +refs/heads/*:refs/remotes/github/*
    [branch "master"]
      remote = github
      merge = refs/heads/master
    [color]
      ui = true
