apiVersion: v1
kind: Pod
metadata:
  name: develop
  namespace: lglns
spec:
  nodeSelector:
    env: test
  containers:
  - name: develop
    image: busybox:1.28
    volumeMounts:
    - name: hostdir
      mountPath: /home
    args:
    - /bin/sh
    - -c
    - sleep 20000
  volumes:
  - name: hostdir
    hostPath:
      path: /home/kbs/lglns/configmaps
