apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-mysql
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      name: mysql
      labels:
        app: mysql-server
    spec:
      hostname: mysql
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysqlport
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: "/run/secrets/kubernetes.io/mysql/mysql-root-password"
        volumeMounts:
        - name: mysql
          mountPath: "/run/secrets/kubernetes.io/mysql"
          readOnly: true
        - name: mysqlvolume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        secret:
          secretName: mysql-secrets
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: ceph-rdb-claim
#        rbd:
#          monitors:
#          - 192.168.122.20:6789
#          - 192.168.122.21:6789
#          - 192.168.122.22:6789
#          pool: kube
#          image: kubernetes-dynamic-pvc-e2cd7827-333e-11e9-9492-0a580af40161
#          user: kube
#          secretRef:
#            name: ceph-user-secret
#          fsType: ext4
#          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql-server
  ports:
  - port: 3306
    targetPort: mysqlport
    nodePort: 30006
