apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer
  namespace: lglns
spec:
  containers:
  - name: producer
    image: busybox:1.28
    volumeMounts:
    - mountPath: /producer_dir
      name: shared-volume
    args:
    - /bin/sh
    - -c
    - echo "Hello, SnowMan" > /producer_dir/hello; sleep 30000
  - name: consumer
    image: busybox:1.28
    volumeMounts:
    - mountPath: /consumer_dir
      name: shared-volume
    args:
    - /bin/sh
    - -c
    - sleep 10; cat /consumer_dir/hello; sleep 29990
  volumes:
  - name: shared-volume
    emptyDir: {}
