apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wp
  namespace: lglns
spec:
  selector:
    matchLabels:
      run: wordpress
  template:
    metadata:
      name: wp
      labels:
        run: wordpress
    spec:
      hostname: wp
      nodeSelector:
        env: test
      containers:
      - name: db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: wordpress
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: wp
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wordpress
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
# 在wordpress容器内做一个health check，检测db的3306端口是否存活，来控制db容器与wordpress容器的启动顺序

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: lglns
spec:
  selector:
    run: wordpress
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
