apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: lglns
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    volumeMounts:
      - name: time
        mountPath: /etc/localtime
        readOnly: true
      - name: secrets
        mountPath: "/etc/foo"
        readOnly: true
    command:
    - /bin/sh
    - -c
    - sleep 1000000
  hostname: busybox
  volumes:
  - hostPath:
      path: /etc/localtime
    name: time
  - name: secrets
    secret:
      secretName: mysql-secrets
      items:
      - key: mysql-password
        path: aaa/db-passwd
      - key: mysql-root-password
        path: aaa/db-root-passwd
      - key: mysql-user
        path: bbb/db-user
